### ISSUE TITLE
SQL0104 - Token , was not valid when using Laravel 5.1 ::paginate(xx)

### ISSUE THREAD

**Issue by BobGenis** [cooperl22/laravel-ibmi#3]
Hello,

I have been using your package on a test project and found a problem when trying to paginate results.  The first page returns fine but subsequent pages throw an SQL error during the prepare step. 

My controller has:

$data = Model::paginate(15);

 The query that is produced is:

select \* from (select *,  row_number() over (order by _field_ asc) as row_num from _table_ ) as temp_table where row_num between 16 and 30;

The problem is the comma in (select *, row_nu...

I was able to work around the error by changing my controller to have:

$data = Model::select('_table_.*')->paginate(xx);

This produced 
select \* from (select _table_.*,  row_number() over (order by _field_ asc) as row_num from _table_ ) as temp_table where row_num between 16 and 30;

and the prepare was successful.

It looks like the Laravel Illuminate Builder is supplying the default of '*" for the columns in a query.  Not sure if there is a way this can be overridden in your package.

This is my first github comment so please forgive me if I've violated any etiquette.

**Comment by BobGenis** [comment]
One addendum:

I'm using 'driver' => 'odbc'

**Comment by cooperl22** [comment]
Fixed by laravel-db2 2.4 dependency
