### ISSUE TITLE
Not getting data from IBMi database

### ISSUE THREAD

**Issue by ryanthomascollier** [cooperl22/laravel-ibmi#4]
Hello,

First off, thank you for developing this. I have a laravel 5.5 application that I am trying to get working with a DB2 database running on a V7R1 IBMi server. 

Here is my database config:

'ibmi' => [
                'driver' => 'db2_ibmi_odbc',
                'driverName' => '{IBM i Access ODBC Driver 64-bit}',
                'host' => 'SYSTEM',
                'username' => 'USER',
                'password' => 'PASSWD',
                'database' => 'DATABASE',
                'prefix' => '',
                'schema' => 'SCHEMA',
                'port' => 50000,
                'date_format' => 'Y-m-d H:i:s',
                // or 'Y-m-d H:i:s.u' / 'Y-m-d-H.i.s.u'...
                'odbc_keywords' => [
                        'SIGNON' => 3,
                        'SSL' => 0,
                        'CommitMode' => 2,
                        'ConnectionType' => 0,
                        'DefaultLibraries' => '',
                        'Naming' => 0,
                        'UNICODESQL' => 0,
                        'DateFormat' => 5,
                        'DateSeperator' => 0,
                        'Decimal' => 0,
                        'TimeFormat' => 0,
                        'TimeSeparator' => 0,
                        'TimestampFormat' => 0,
                        'ConvertDateTimeToChar' => 0,
                        'BLOCKFETCH' => 1,'BlockSizeKB' => 32,
                        'AllowDataCompression' => 1,
                        'CONCURRENCY' => 0,
                        'LAZYCLOSE' => 0,
                        'MaxFieldLength' => 15360,
                        'PREFETCH' => 0,
                        'QUERYTIMEOUT' => 1,
                        'DefaultPkgLibrary' => 'QGPL',
                        'DefaultPackage' => 'A /DEFAULT(IBM),2,0,1,0',
                        'ExtendedDynamic' => 0,
                        'QAQQINILibrary' => '',
                        'SQDIAGCODE' => '',
                        'LANGUAGEID' => 'ENU',
                        'SORTTABLE' => '',
                        'SortSequence' => 0,
                        'SORTWEIGHT' => 0,
                        'AllowUnsupportedChar' => 0,
                        'CCSID' => 1208,
                        'GRAPHIC' => 0,
                        'ForceTranslation' => 0,
                        'ALLOWPROCCALLS' => 0,
                        'DB2SQLSTATES' => 0,
                        'DEBUG' => 0,
                        'TRUEAUTOCOMMIT' => 0,
                        'CATALOGOPTIONS' => 3,
                        'LibraryView' => 0,
                        'ODBCRemarks' => 0,
                        'SEARCHPATTERN' => 1,
                        'TranslationDLL' => '',
                        'TranslationOption' => 0,
                        'MAXTRACESIZE' => 0,
                        'MultipleTraceFiles' => 1,
                        'TRACE' => 0,
                        'TRACEFILENAME' => '','ExtendedColInfo' => 0,
                ],

I can successfully run the migration, and actually insert some data into my database. The problem comes into play when I try to retrieve any data through my application. I was wondering if you've seen this before?

Thanks,

**Comment by wstaples** [comment]
How are you attempting to query your database?

**Comment by ryanthomascollier** [comment]
Hello,

I actually discovered what the issue is. I'm a little embarrassed to admit
it but the issue was being caused by the field names being in all
uppercase. When I originally built my app I used a MySQL backend which has
case sensitive field names. Changing every reference to the field names in
my app resolved the issue.

Thanks,

**Comment by cooperl22** [comment]
OK. Glad you solved the issue. Closing it!
