### ISSUE TITLE
Drivers for linux and mac

### ISSUE THREAD

**Issue by RiccardoFrancescato** [cooperl22/laravel-ibmi#5]
This is not a code issue, i have googled a lot to find drivers and installation guides but, without success.
 I'm asking you where i can find drivers for ibm i (AS400) and how to install them.
Thanks

**Comment by jacobdekeizer** [comment]
Did you resolve this issue?
I have the same problem

**Comment by cooperl22** [comment]
See https://www.ibm.com/support/pages/ibm-i-access-client-solutions

**Comment by RiccardoFrancescato** [comment]
@jacobdekeizer I'm sorry but no, i do not found any working driver, IBM website is terrible and the drivers are more terrible.
I configured a MS Sql server and set db2 as linked server but is slower and less efficient.

**Comment by cooperl22** [comment]
@RiccardoFrancescato 
[https://www.ibm.com/support/pages/obtaining-ibm-i-access-client-solutions](url)
